name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push to master branch with changes in __about__.py
  push:
    branches:
      - "master"
    paths:
      - "lightning/__about__.py"

# based on https://github.com/pypa/gh-action-pypi-publish
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: >-
        python -m pip install --user --upgrade setuptools wheel

    - name: Install Lightning
      run: |
        python -m pip install -r requirements.txt --quiet
        python -m pip install . --quiet

    - name: Build
      run: >-
        python setup.py sdist bdist_wheel

    - name: Publish to Custom PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.LIGHTNING_PYPI_USER }}
        password: ${{ secrets.LIGHTNING_PYPI_PASSWORD }}
        # if you are changing this to another server, change the image builder in the cloud to fetch from new URL
        repository_url: https://us-central1-python.pkg.dev/grid-backend-266721/xpi/
